// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameSpaceProvisioner) DeepCopyInto(out *NameSpaceProvisioner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameSpaceProvisioner.
func (in *NameSpaceProvisioner) DeepCopy() *NameSpaceProvisioner {
	if in == nil {
		return nil
	}
	out := new(NameSpaceProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NameSpaceProvisioner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameSpaceProvisionerList) DeepCopyInto(out *NameSpaceProvisionerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NameSpaceProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameSpaceProvisionerList.
func (in *NameSpaceProvisionerList) DeepCopy() *NameSpaceProvisionerList {
	if in == nil {
		return nil
	}
	out := new(NameSpaceProvisionerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NameSpaceProvisionerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameSpaceProvisionerSpec) DeepCopyInto(out *NameSpaceProvisionerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameSpaceProvisionerSpec.
func (in *NameSpaceProvisionerSpec) DeepCopy() *NameSpaceProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(NameSpaceProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameSpaceProvisionerStatus) DeepCopyInto(out *NameSpaceProvisionerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameSpaceProvisionerStatus.
func (in *NameSpaceProvisionerStatus) DeepCopy() *NameSpaceProvisionerStatus {
	if in == nil {
		return nil
	}
	out := new(NameSpaceProvisionerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserNameSpace) DeepCopyInto(out *UserNameSpace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserNameSpace.
func (in *UserNameSpace) DeepCopy() *UserNameSpace {
	if in == nil {
		return nil
	}
	out := new(UserNameSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserNameSpace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserNameSpaceList) DeepCopyInto(out *UserNameSpaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserNameSpace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserNameSpaceList.
func (in *UserNameSpaceList) DeepCopy() *UserNameSpaceList {
	if in == nil {
		return nil
	}
	out := new(UserNameSpaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserNameSpaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserNameSpaceSpec) DeepCopyInto(out *UserNameSpaceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserNameSpaceSpec.
func (in *UserNameSpaceSpec) DeepCopy() *UserNameSpaceSpec {
	if in == nil {
		return nil
	}
	out := new(UserNameSpaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserNameSpaceStatus) DeepCopyInto(out *UserNameSpaceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserNameSpaceStatus.
func (in *UserNameSpaceStatus) DeepCopy() *UserNameSpaceStatus {
	if in == nil {
		return nil
	}
	out := new(UserNameSpaceStatus)
	in.DeepCopyInto(out)
	return out
}
